name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Stap 1: Repository uitchecken
      - name: Checkout repository
        uses: actions/checkout@v2

      # Stap 2: PHP instellen
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, gd, xml, pdo, tokenizer
          coverage: xdebug

      # Stap 3: Dependencies installeren
      - name: Install dependencies
        working-directory: laravel
        run: composer install --prefer-dist --no-progress

      # Stap 4: .env file instellen
      - name: Set up .env file
        working-directory: laravel
        run: cp .env.example .env

      # Stap 5: Databaseconfiguratie bijwerken voor CI
      - name: Update database configuration
        working-directory: laravel
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=testing/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=rootpassword/' .env

      # Stap 6: Applicatiesleutel genereren
      - name: Generate application key
        working-directory: laravel
        run: php artisan key:generate

      # Stap 7: Wachten tot MySQL beschikbaar is
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin --user=root --password=rootpassword --host=127.0.0.1 --port=3306 ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      # Stap 8
