name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root_password  # Gebruik hetzelfde wachtwoord hier en in .env.testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug

      - name: Install dependencies
        working-directory: laravel
        run: composer install --prefer-dist --no-progress

      - name: Wait for MySQL to be ready
        run: sleep 30  # Simpel wachten voor 30 seconden zodat MySQL de tijd heeft om op te starten

      - name: Run migrations
        working-directory: laravel
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: root_password
        run: php artisan migrate --env=testing --force

      - name: Run Unit Tests and Generate Coverage Report (from Vendor)
        working-directory: laravel
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml
          else
            echo "PHPUnit not found in vendor, installing globally."
            composer global require phpunit/phpunit:^9.0
            ~/.composer/vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml
          fi

      - name: Verify Coverage Report Exists
        working-directory: laravel
        run: ls -la

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=project-cin \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://localhost:9000 \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
