name: Laravel CI with Database Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List root directory contents
        run: ls -al

      - name: Check Laravel directory contents
        run: ls -al laravel

      - name: Install dependencies
        working-directory: ./laravel
        run: composer install --prefer-dist --no-scripts --no-progress --no-interaction

      - name: Ensure .env exists
        working-directory: ./laravel
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Generate application key
        working-directory: ./laravel
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./laravel
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./laravel
        run: php artisan test
